// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB88chgyJgFsUaQZdHerDlC7DA12fYS314',
    appId: '1:424554406739:web:034ad60c300052cab437a6',
    messagingSenderId: '424554406739',
    projectId: 'tik-tok-clone-flutter',
    authDomain: 'tik-tok-clone-flutter.firebaseapp.com',
    storageBucket: 'tik-tok-clone-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJpt86kv6TLMa3W8OVSl6flG8geLZ90pc',
    appId: '1:424554406739:android:2daf9549c6e1c7c8b437a6',
    messagingSenderId: '424554406739',
    projectId: 'tik-tok-clone-flutter',
    storageBucket: 'tik-tok-clone-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiRziO7gUfUB1auGHp5cVFmKLGiHEaa7Y',
    appId: '1:424554406739:ios:ff5e9f625008e8a3b437a6',
    messagingSenderId: '424554406739',
    projectId: 'tik-tok-clone-flutter',
    storageBucket: 'tik-tok-clone-flutter.appspot.com',
    iosBundleId: 'com.example.tikTokClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiRziO7gUfUB1auGHp5cVFmKLGiHEaa7Y',
    appId: '1:424554406739:ios:ff5e9f625008e8a3b437a6',
    messagingSenderId: '424554406739',
    projectId: 'tik-tok-clone-flutter',
    storageBucket: 'tik-tok-clone-flutter.appspot.com',
    iosBundleId: 'com.example.tikTokClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB88chgyJgFsUaQZdHerDlC7DA12fYS314',
    appId: '1:424554406739:web:79bac84751b666b7b437a6',
    messagingSenderId: '424554406739',
    projectId: 'tik-tok-clone-flutter',
    authDomain: 'tik-tok-clone-flutter.firebaseapp.com',
    storageBucket: 'tik-tok-clone-flutter.appspot.com',
  );
}
